services:
    postgres:
        image: postgres:16
        environment:
            POSTGRES_DB: app
            POSTGRES_USER: app
            POSTGRES_PASSWORD: app
        ports:
            - "5433:5432"
        volumes:
            - ./_data/postgres:/var/lib/postgresql/data

    minio:
        image: minio/minio:latest
        environment:
            MINIO_ROOT_USER: minio
            MINIO_ROOT_PASSWORD: minio12345
        command: server /data --console-address ":9001"
        ports:
            - "9000:9000"
            - "9001:9001"
        volumes:
            - ./_data/minio:/data
