name: Deploy
on:
    push:
        branches: ["main"]

jobs:
    build-and-deploy:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build+Push web
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: apps/web/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/your-stack-web:latest
                      ghcr.io/${{ github.repository_owner }}/your-stack-web:${{ github.sha }}

            - name: Build+Push ws
              uses: docker/build-push-action@v6
              with:
                  context: .
                  file: apps/ws/Dockerfile
                  push: true
                  tags: |
                      ghcr.io/${{ github.repository_owner }}/your-stack-ws:latest
                      ghcr.io/${{ github.repository_owner }}/your-stack-ws:${{ github.sha }}

            - name: Trigger Coolify deploy (web)
              run: curl -fsS -X POST "${{ secrets.COOLIFY_WEB_HOOK_URL }}"
            - name: Trigger Coolify deploy (ws)
              run: curl -fsS -X POST "${{ secrets.COOLIFY_WS_HOOK_URL }}"
